apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-args
data:
  args.txt: |
    --model
    TinyLlama/TinyLlama-1.1B-Chat-v1.0
    --host
    0.0.0.0
    --port
    8080
    --gpu-memory-utilization
    0.90
    --max-model-len
    2048