kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - name: container
          image: 'quay.io/mmartofe/ai-chat-ui:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: chat-ui
                  key: MODEL_NAME
            - name: MODEL_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-ui
                  key: MODEL_SERVER_URL
          resources:
             limits:
                nvidia.com/gpu: "1"
                memory: "50Mi"
                cpu: "0.3"
             requests:
                memory: "10Mi"
                cpu: "0.1"
